spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
  gateway:
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: '*'
          allowedMethods:
            - POST
            - GET
            - PUT
            - OPTIONS
            - DELETE
    routes:
      - id: a-service
        uri: http://localhost:18081
        predicates:
          - Path=/aservice/**
      - id: b-service
        uri: http://localhost:18082
        predicates:
          - Path=/bservice/**